class_name DontDodgeLocalization
extends Node

signal locale_changed(locale: StringName)

const SETTINGS_PATH: String = "user://dont_dodge_settings.cfg"
const SETTINGS_SECTION: String = "localization"
const SETTINGS_KEY: String = "locale"
const DEFAULT_LOCALE: StringName = &"ko"
const SUPPORTED_LOCALES: Array[StringName] = [&"ko", &"en"]

const CATALOG: Dictionary = {
	&"ko": {
		&"title.subtitle": "던전의 위협을 베고 · 밀치고 · 직접 피하라",
		&"title.controls": "이동 방향키 · Q 베기 · W 회피 · E 무효화 · R 궁극기\\n회피와 무효화는 같은 방어 2칸을 공유합니다",
		&"title.start": "게임 시작",
		&"title.start_tooltip": "일반 전투를 시작합니다",
		&"title.mode": "전투 모드",
		&"title.challenge": "도전 모드",
		&"title.challenge_tooltip": "랜덤 디버프 하나를 안고 90초 생존",
		&"title.training": "훈련장",
		&"title.training_tooltip": "무기와 강화 트리를 고르고 원하는 적을 소환합니다",
		&"title.guide": "전투 가이드",
		&"title.guide_tooltip": "DON'T DODGE 조작과 대응 가이드",
		&"title.language": "언어",
		&"language.ko": "한국어",
		&"language.en": "English",
		&"audio.bgm_on": "BGM: 켜짐",
		&"audio.bgm_off": "BGM: 꺼짐",
		&"audio.sfx_on": "효과음: 켜짐",
		&"audio.sfx_off": "효과음: 꺼짐",
		&"training.setup_title": "훈련장 설정",
		&"training.setup_subtitle": "시간 제한 없이 원하는 빌드와 적을 직접 시험합니다.",
		&"training.weapon": "무기",
		&"training.weapon_tooltip": "훈련에 사용할 무기",
		&"training.start_level": "시작 레벨",
		&"training.technique": "레벨 2 기술",
		&"training.ultimate": "레벨 3 궁극기",
		&"training.level_0": "LV 0 · 기본 상태",
		&"training.level_1": "LV 1 · 무기 적용",
		&"training.level_2": "LV 2 · 기술까지 적용",
		&"training.level_3": "LV 3 · 궁극기까지 적용",
		&"training.level_0_detail": "무기와 강화 효과 없이 시작",
		&"training.level_1_detail": "선택한 무기를 적용하고 시작",
		&"training.level_2_detail": "무기와 레벨 2 기술을 적용",
		&"training.level_3_detail": "전체 빌드를 적용하고 시작",
		&"training.level_badge": "LV %d",
		&"training.weapon_fallback": "무기",
		&"training.technique_fallback": "기술",
		&"training.ultimate_fallback": "궁극기",
		&"training.weapon_card_role": "무기 스타일",
		&"training.technique_card_role": "레벨 2 기술",
		&"training.ultimate_card_role": "레벨 3 궁극기",
		&"training.locked_at_level": "잠김 · LV%d 필요",
		&"training.hint": "훈련 중에는 자동 웨이브와 90초 종료가 없습니다. 전투 화면에서 적을 소환하고 리셋할 수 있습니다.",
		&"training.back": "로비로 돌아가기",
		&"training.enter": "훈련장 입장",
		&"training.summary_title": "현재 빌드",
		&"training.summary": "%s\\n%s\\n%s\\n%s",
		&"training.summary_level": "시작 %s",
		&"training.summary_weapon": "무기 · %s\\n%s",
		&"training.summary_option": "%s · %s\\n%s",
		&"training.summary_locked": "잠김 · LV%d에서 선택 가능",
		&"guide.title": "DON'T DODGE · 전투 가이드",
		&"guide.subtitle": "위협을 보고 가장 알맞은 대응을 고르세요.",
		&"guide.attack_title": "가까운 적",
		&"guide.attack_detail": "Q\\n집중 베기로 처치\\n근접 적의 공격 예고가 보이면 사용",
		&"guide.dodge_title": "위험한 공격",
		&"guide.dodge_detail": "W\\n무적 이동으로 회피\\n강한 공격 예고가 보이면 이동하며 사용\\n처음 0.15초는 정밀 회피",
		&"guide.negate_title": "투사체와 혼전",
		&"guide.negate_detail": "E\\n적과 탄환을 무효화\\n탄환이나 혼전이 보이면 사용",
		&"guide.ultimate_title": "게이지 충전",
		&"guide.ultimate_detail": "레벨 3 해금 후 R\\n궁극기로 전장 정리",
		&"guide.resource_hint": "W와 E는 같은 방어 스택 2칸을 공유합니다. 상황에 맞춰 아껴 쓰세요.",
		&"guide.start": "전투 시작",
		&"guide.close": "닫기",
		&"tutorial.hint_melee": "가까운 적은 Q로 처치할 수 있습니다.",
		&"tutorial.hint_negate": "탄환이나 혼전은 E로 위험을 지울 수 있습니다.",
		&"tutorial.hint_dodge": "강한 공격 예고가 보이면 W로 이동하며 회피하세요.",
		&"tutorial.hint_defense": "W와 E는 방어 스택을 공유합니다.",
		&"tutorial.hint_ultimate": "레벨 3 궁극기가 해금되었습니다. R로 사용하세요.",
		&"tutorial.skip": "튜토리얼 건너뛰기",
		&"hud.training_time": "훈련 시간",
		&"hud.remaining_time": "남은 시간",
		&"hud.training": "훈련장",
		&"hud.wave": "웨이브 %d / %d",
		&"hud.unlimited": "시간 제한 없음",
		&"hud.in_progress": "진행 중",
		&"hud.paused": "일시정지",
		&"hud.upgrade_select": "강화 선택",
		&"hud.cleanup_wait": "정리 대기",
		&"hud.clearing": "소탕 중",
		&"hud.player_dead": "전투 불능",
		&"hud.result": "결과 확인",
		&"hud.challenge_reveal": "디버프 추첨",
		&"hud.base_build": "기본 베기 · 무기 선택 전",
		&"hud.challenge": "CHALLENGE · %s",
		&"hud.challenge_ready": "룰렛 준비 중",
		&"hud.level_max": "LV %d  ·  MAX",
		&"hud.level_xp": "LV %d  ·  XP %d / %d",
		&"action.attack": "베기",
		&"action.dodge": "회피",
		&"action.negate": "무효화",
		&"action.ultimate": "궁극",
		&"action.locked": "잠김",
		&"action.attack_cooldown_display": "다음 베기 %.1f초",
		&"action.defense_display": "방어 %d/%d",
		&"action.defense_locked_display": "방어 %d/%d\\n잠김",
		&"action.attack_tooltip_cooldown": "근접 베기\\nQ · 피해 %d · 공격속도 %+d%%\\n다음 베기까지 %.2f초",
		&"action.attack_tooltip_ready": "근접 베기\\nQ · 피해 %d · 공격속도 %+d%%\\n범위 %d · 각도 %d° · 간격 %.2f초",
		&"action.dodge_tooltip": "회피\\nW · 이동 방향으로 무적 돌진.\\n방어 스택 %d/%d · 사용 비용 %d칸%s",
		&"action.dodge_twice_suffix": " · 두 번 사용 가능",
		&"action.negate_tooltip": "무효화\\nE · 방어 1칸으로 적과 투사체를 제거합니다.\\n%s",
		&"action.negate_disabled": "단검에서는 사용할 수 없습니다.",
		&"action.defense_state": "방어 스택 %d/%d",
		&"action.ultimate_ready": "준비 완료",
		&"action.ultimate_charge": "충전 %d%%",
		&"action.ultimate_locked_detail": "레벨 3에서 무기별 궁극기를 해금합니다.",
		&"action.ultimate_select_detail": "레벨 3에서 궁극기를 선택하세요.",
		&"pause.title": "일시정지",
		&"pause.hint": "Esc 또는 Ⅱ 버튼으로 계속하기",
		&"pause.challenge": "도전 · %s",
		&"pause.resume": "계속하기",
		&"pause.restart": "다시 시작",
		&"pause.main": "메인으로",
		&"pause.button_tooltip": "일시정지 · Esc",
		&"upgrade.hint": "카드를 클릭하거나 방향키 + Enter로 선택",
		&"upgrade.weapon_select": "무기 선택",
		&"upgrade.technique_select": "[%s] 기술 선택",
		&"upgrade.ultimate_unlock": "[%s] 궁극기 해금",
		&"upgrade.level_title": "레벨 %d\\n%s",
		&"upgrade.role": "전투 선택지",
		&"upgrade.fallback": "강화",
		&"upgrade.immediate": "선택 즉시 무기 효과가 적용됩니다.",
		&"upgrade.effect": "효과 · %s%s",
		&"upgrade.rule": "\\n규칙 · %s",
		&"upgrade.weakness": "약점 · %s",
		&"upgrade.condition": "조건 · 선택 즉시 적용",
		&"upgrade.applied": "강화 적용 · %s",
		&"upgrade.applied_detail": "효과가 적용되었습니다.",
		&"training.controls_title": "훈련장 도구",
		&"training.controls_hint": "원하는 위협을 골라 빌드를 바로 시험하세요.",
		&"training.summon_group": "위협 소환",
		&"training.field_group": "필드 관리",
		&"training.navigation_group": "훈련 메뉴",
		&"training.spawn_melee": "근접형 위협",
		&"training.spawn_ranged": "원거리형 위협",
		&"training.spawn_charger": "돌진형 위협",
		&"training.spawn_volley": "연사형 위협",
		&"training.spawn_elite": "정예형 위협",
		&"training.enemy_melee_role": "가까이 붙어 압박하는 위협",
		&"training.enemy_ranged_role": "거리를 두고 탄환을 쏘는 위협",
		&"training.enemy_charger_role": "긴 예고 후 직선으로 돌진",
		&"training.enemy_volley_role": "여러 방향으로 탄환을 흩뿌림",
		&"training.enemy_elite_role": "강한 체력으로 버티며 보상을 남김",
		&"training.clear": "필드 정리",
		&"training.reset": "훈련 초기화",
		&"training.exit": "훈련장 나가기",
		&"training.spawn_feedback": "훈련 적 소환 · %s",
		&"training.reset_feedback": "훈련장 리셋",
		&"enemy.melee": "근접",
		&"enemy.ranged": "원거리",
		&"enemy.charger": "돌진",
		&"enemy.volley": "연사",
		&"enemy.elite": "정예",
		&"challenge.title": "도전 모드 · 디버프 룰렛",
		&"challenge.hint": "이번 전투에 적용될 제약을 하나 추첨합니다.",
		&"challenge.spinning": "룰렛을 돌리는 중...",
		&"challenge.result": "결과 확정 · %s\\n%s",
		&"challenge.start": "도전 시작",
		&"feedback.title_normal": "DON'T DODGE",
		&"feedback.title_challenge": "도전 · %s",
		&"feedback.training": "훈련장 · 시간 제한 없음",
		&"feedback.upgrade_applied": "%s 적용%s",
		&"feedback.ultimate_ready_suffix": " · 궁극기 준비 완료 · R",
		&"feedback.attack_miss": "공격이 빗나갔습니다",
		&"feedback.dodge_pending": "회피 준비 중",
		&"feedback.defense_empty": "방어 스택 부족",
		&"feedback.dagger_stealth": "발도 · 은신",
		&"feedback.spear_breakthrough": "돌파 준비",
		&"feedback.dagger_negate_locked": "E 잠김 · 단검은 회피에 집중합니다",
		&"feedback.front_guard": "정면 방어",
		&"feedback.no_negate_target": "무효화할 대상이 없습니다",
		&"feedback.no_projectile": "막을 탄환이 없습니다",
		&"feedback.bullet_cut": "탄막 절단 준비 · 다음 Q 3열 창격",
		&"feedback.ultimate_locked": "궁극기 잠김 · 레벨 3에서 해금",
		&"feedback.ultimate_charge": "궁극기 충전 %d%%",
		&"feedback.ultimate_missing": "궁극기 효과를 찾을 수 없습니다",
		&"feedback.assassination_no_target": "암살 표식 · 대상 없음",
		&"feedback.ground_suppression": "대지 진압 · %d명 처치 · %d명 제압",
		&"feedback.wave_pressure": "웨이브 %d · 압박 상승",
		&"feedback.counter_ready": "받아냄 · 다음 공격 강화",
		&"feedback.perfect_dodge": "완벽 · 정밀 회피",
		&"feedback.ghost_step": "유령보폭 · 이동 가속",
		&"feedback.elite_down": "정예 처치 · 회복 아이템 생성",
		&"feedback.ultimate_ready": "궁극기 준비 완료 · R",
		&"feedback.shadow_frenzy_complete": "그림자 폭주 · %d명 처리 완료",
		&"feedback.assassination_complete": "암살 표식 · 강적 처치",
		&"feedback.ground_suppression_complete": "대지 진압 완료",
		&"feedback.frontline_break_complete": "전선 돌파 · 전선에 진입",
		&"feedback.sky_pierce_complete": "천공일섬 · 3회 관통",
		&"feedback.spear_formation_complete": "창진 · 1회 관통",
		&"result.clear": "90초 생존 · WAVE %d 잔당 소탕 성공",
		&"result.death": "전투 불능",
		&"result.normal_mode": "일반 전투",
		&"result.challenge_mode": "도전 · %s",
		&"result.summary": "%s\\n%s\\n처치 %d · 피격 %d · 회피 %d · 무효화 %d\\n완벽 회피 %d · 인터럽트 %d · 투사체 삭제 %d\\n궁극기 %d회",
		&"result.restart": "다시 시작",
		&"result.lobby": "로비로 가기",
		&"data.dagger.title": "단검",
		&"data.dagger.subtitle": "빠르게 한 명씩 제거하는 암살 무기",
		&"data.dagger.description": "W로 위험을 통과하고, 빠른 단일 대상 공격으로 적을 연달아 처치합니다.",
		&"data.dagger.detail": "공격속도 +35% · 이동속도 +8% · 단일 대상 공격",
		&"data.dagger.icon_label": "공격형",
		&"data.dagger.rule": " W 특화 · 한 번에 한 명만 공격",
		&"data.dagger.weakness": "낮은 체력 · E 사용 불가 · 짧은 사거리",
		&"data.tech_dagger_draw.title": "발도",
		&"data.tech_dagger_draw.description": "W가 끝난 뒤 잠시 적의 시야에서 사라집니다.",
		&"data.tech_dagger_draw.detail": "W 종료 후 0.4초 은신 · 은신 중 첫 공격 피해 +2 · 기존 투사체는 유지",
		&"data.tech_dagger_draw.icon_label": "회피 연계",
		&"data.tech_dagger_flurry.title": "난무",
		&"data.tech_dagger_flurry.description": "세 번째 공격이 두 번의 단일 대상 베기로 이어집니다.",
		&"data.tech_dagger_flurry.detail": "첫 대상 처치 시 두 번째 베기가 가까운 적으로 전환 · 잔상과 별도 타격음",
		&"data.tech_dagger_flurry.icon_label": "연속 공격",
		&"data.tech_dagger_ghost_step.title": "유령보폭",
		&"data.tech_dagger_ghost_step.description": "적을 처치할 때마다 다음 목표로 빠르게 넘어갑니다.",
		&"data.tech_dagger_ghost_step.detail": "적 처치 후 0.6초 동안 이동속도 +20% · 처치 시 지속시간 갱신",
		&"data.tech_dagger_ghost_step.icon_label": "이동 강화",
		&"data.ult_dagger_shadow_frenzy.title": "그림자 폭주",
		&"data.ult_dagger_shadow_frenzy.description": "가까운 적 셋을 차례로 베며 전장을 가로지릅니다.",
		&"data.ult_dagger_shadow_frenzy.detail": "최대 3명 · 대상마다 표식 → 돌진 → 4 피해 · 시퀀스 중 무적",
		&"data.ult_dagger_shadow_frenzy.icon_label": "다수 암살",
		&"data.ult_dagger_assassination_mark.title": "암살 표식",
		&"data.ult_dagger_assassination_mark.description": "가장 위협적인 적에게 표식을 남기고 뒤로 순간이동해 집중 공격합니다.",
		&"data.ult_dagger_assassination_mark.detail": "정예·차저 우선 지정 · 표식 → 대상 뒤로 돌진 · 4 피해 3연격",
		&"data.ult_dagger_assassination_mark.icon_label": "단일 암살",
		&"data.guardian_mace.title": "수호철퇴",
		&"data.guardian_mace.subtitle": "정면에서 공격을 받아내고 전선을 지키는 무기",
		&"data.guardian_mace.description": "E로 정면의 투사체와 공격을 받아치며 W는 방어 스택 두 칸을 쓰는 비상 이동기입니다.",
		&"data.guardian_mace.detail": "정면 방어 · 강한 넉백 · 회피 비용 2칸 · 최대 체력 3",
		&"data.guardian_mace.icon_label": "방어형",
		&"data.guardian_mace.rule": "E 주력 · W 비용 2칸 · 정면 방어",
		&"data.guardian_mace.weakness": "느린 이동 · 측후면 공격에 취약 · 방어 자원 의존",
		&"data.tech_mace_counter.title": "받아치기",
		&"data.tech_mace_counter.description": "E로 막아낸 뒤 1.2초 안에 철퇴 강타로 반격합니다.",
		&"data.tech_mace_counter.detail": "방어 성공 후 다음 Q 피해 +2 · 넉백 강화 · 공격 준비 중단",
		&"data.tech_mace_counter.icon_label": "반격 강화",
		&"data.tech_mace_reflect_wave.title": "반사 파동",
		&"data.tech_mace_reflect_wave.description": "되받아친 투사체가 적중 지점에서 주변 적까지 휩쓸어갑니다.",
		&"data.tech_mace_reflect_wave.detail": "반사 투사체 적중 시 작은 충격파 · 주변 최대 2명 추가 타격",
		&"data.tech_mace_reflect_wave.icon_label": "반사 공격",
		&"data.tech_mace_suppress.title": "제압 강타",
		&"data.tech_mace_suppress.description": "공격을 준비하는 적을 철퇴 한 방으로 끊습니다.",
		&"data.tech_mace_suppress.detail": "근접 적·차저의 공격 준비 중단 · 강타 연출 · 내부 재사용 2.5초",
		&"data.tech_mace_suppress.icon_label": "공격 중단",
		&"data.ult_mace_ground_suppression.title": "대지 진압",
		&"data.ult_mace_ground_suppression.description": "짧은 예고 뒤 주변을 내려찍어 전장을 진압합니다.",
		&"data.ult_mace_ground_suppression.detail": "예고 → 360도 충격파 · 일반 적 처치 · 정예·차저 피해 및 공격 중단",
		&"data.ult_mace_ground_suppression.icon_label": "광역 제압",
		&"data.ult_mace_frontline_break.title": "전선 돌파",
		&"data.ult_mace_frontline_break.description": "원거리 전선 또는 마지막 이동 방향으로 방어 돌진합니다.",
		&"data.ult_mace_frontline_break.detail": "경로 예고 → 투사체 제거 → 도착 지점 광역 철퇴 공격 · 대상이 없어도 실행",
		&"data.ult_mace_frontline_break.icon_label": "전선 돌파",
		&"data.battle_spear.title": "전투창",
		&"data.battle_spear.subtitle": "긴 직선과 관통으로 전장을 가르는 무기",
		&"data.battle_spear.description": "좁고 긴 공격으로 적을 일렬로 꿰뚫고 W와 E를 이어 다음 공격을 준비합니다.",
		&"data.battle_spear.detail": "사거리 +60 · 기본 공격 관통 · 투사체 무효화 · 좁은 공격각",
		&"data.battle_spear.icon_label": "관통형",
		&"data.battle_spear.rule": "좁고 긴 기본 공격 · 일렬 관통",
		&"data.battle_spear.weakness": "좁은 공격각 · 측면 혼전에 취약",
		&"data.tech_spear_breakthrough.title": "돌파",
		&"data.tech_spear_breakthrough.description": "W로 적을 직접 찌르면 다음 공격이 한 번 더 꿰뚫습니다.",
		&"data.tech_spear_breakthrough.detail": "W가 적에게 적중하면 0.8초 동안 다음 Q에 추가 관통 창격",
		&"data.tech_spear_breakthrough.icon_label": "돌진 연계",
		&"data.tech_spear_bullet_cut.title": "탄막 절단",
		&"data.tech_spear_bullet_cut.description": "E로 탄막을 걷어내면 다음 공격이 세 줄의 창격으로 바뀝니다.",
		&"data.tech_spear_bullet_cut.detail": "투사체 2개 이상 제거 시 다음 Q가 좁은 3열 창격 · 0.9초 유지",
		&"data.tech_spear_bullet_cut.icon_label": "탄막 대응",
		&"data.tech_spear_edge_pressure.title": "끝자락 견제",
		&"data.tech_spear_edge_pressure.description": "사거리 끝에서 적을 꿰뚫어 움직임과 공격을 묶습니다.",
		&"data.tech_spear_edge_pressure.detail": "사거리 바깥 30% 적중 시 0.65초 감속·표식 · 준비 중인 공격 중단",
		&"data.tech_spear_edge_pressure.icon_label": "거리 유지",
		&"data.ult_spear_sky_pierce.title": "천공일섬",
		&"data.ult_spear_sky_pierce.description": "예고한 직선을 한 번에 꿰뚫어 전장의 선을 정리합니다.",
		&"data.ult_spear_sky_pierce.detail": "강적 또는 마지막 이동 방향 기준 · 3회 관통 · 회당 피해 3 · 대상 없음도 실행",
		&"data.ult_spear_sky_pierce.icon_label": "직선 폭발",
		&"data.ult_spear_formation.title": "창진",
		&"data.ult_spear_formation.description": "적과 연결된 직선을 플레이어 중심으로 화면 전체에 가르고 한 번 관통합니다.",
		&"data.ult_spear_formation.detail": "표식 대상 우선 자동 조준 · 맵 양끝까지 직선 범위 · 1회 공격 · 피해 3",
		&"data.ult_spear_formation.icon_label": "지역 통제",
		&"challenge.slow_defense.title": "느린 방어 회복",
		&"challenge.slow_defense.description": "방어 스택 회복 시간이 5초에서 7초로 늘어납니다.",
		&"challenge.ultimate_famine.title": "궁극기 빈곤",
		&"challenge.ultimate_famine.description": "궁극기 획득량이 75%로 감소합니다.",
		&"challenge.dry_dungeon.title": "메마른 던전",
		&"challenge.dry_dungeon.description": "전투 중 회복 아이템이 등장하지 않습니다.",
		&"challenge.bullet_overload.title": "탄막 과부하",
		&"challenge.bullet_overload.description": "Volley 적이 투사체를 하나 더 발사합니다.",
	},
	&"en": {
		&"title.subtitle": "Cut through dungeon threats. Push them back. Or dodge them yourself.",
		&"title.controls": "Arrow keys Move · Q Attack · W Dodge · E Nullify · R Ultimate\\nDodge and Nullify share two defense charges",
		&"title.start": "Start Game",
		&"title.start_tooltip": "Start a standard run",
		&"title.mode": "Game Mode",
		&"title.challenge": "Challenge Mode",
		&"title.challenge_tooltip": "Survive 90 seconds with one random debuff",
		&"title.training": "Training Grounds",
		&"title.training_tooltip": "Choose a weapon and upgrade path, then summon the enemies you want",
		&"title.guide": "Dodge Guide",
		&"title.guide_tooltip": "DON'T DODGE controls and response guide",
		&"title.language": "Language",
		&"language.ko": "Korean",
		&"language.en": "English",
		&"audio.bgm_on": "BGM: On",
		&"audio.bgm_off": "BGM: Off",
		&"audio.sfx_on": "SFX: On",
		&"audio.sfx_off": "SFX: Off",
		&"training.setup_title": "Training Setup",
		&"training.setup_subtitle": "Test any build against any enemy with no time limit.",
		&"training.weapon": "Weapon",
		&"training.weapon_tooltip": "Weapon used for training",
		&"training.start_level": "Starting Level",
		&"training.technique": "Level 2 Technique",
		&"training.ultimate": "Level 3 Ultimate",
		&"training.level_0": "LV 0 · Base state",
		&"training.level_1": "LV 1 · Weapon equipped",
		&"training.level_2": "LV 2 · Technique equipped",
		&"training.level_3": "LV 3 · Ultimate equipped",
		&"training.level_0_detail": "Start without a weapon or upgrades",
		&"training.level_1_detail": "Start with the selected weapon",
		&"training.level_2_detail": "Apply the weapon and a level 2 technique",
		&"training.level_3_detail": "Start with the full build applied",
		&"training.level_badge": "LV %d",
		&"training.weapon_fallback": "Weapon",
		&"training.technique_fallback": "Technique",
		&"training.ultimate_fallback": "Ultimate",
		&"training.weapon_card_role": "Weapon style",
		&"training.technique_card_role": "Level 2 Technique",
		&"training.ultimate_card_role": "Level 3 Ultimate",
		&"training.locked_at_level": "Locked · Requires LV%d",
		&"training.hint": "Training has no automatic waves or 90-second finish. Summon enemies and reset the fight from the combat screen.",
		&"training.back": "Back to Lobby",
		&"training.enter": "Enter Training",
		&"training.summary_title": "Current Build",
		&"training.summary": "%s\\n%s\\n%s\\n%s",
		&"training.summary_level": "Start %s",
		&"training.summary_weapon": "Weapon · %s\\n%s",
		&"training.summary_option": "%s · %s\\n%s",
		&"training.summary_locked": "Locked · Available at LV%d",
		&"guide.title": "DON'T DODGE · Combat Guide",
		&"guide.subtitle": "Read the threat and choose the right response.",
		&"guide.attack_title": "Close threat",
		&"guide.attack_detail": "Q\\nCut it down with Attack\\nUse it when a close enemy telegraphs",
		&"guide.dodge_title": "Dangerous attack",
		&"guide.dodge_detail": "W\\nDodge with an invulnerable dash\\nMove with it when a heavy attack telegraphs\\nThe first 0.15 seconds is a perfect dodge",
		&"guide.negate_title": "Projectiles and chaos",
		&"guide.negate_detail": "E\\nNullify enemies and projectiles\\nUse it for bullets or close-quarters chaos",
		&"guide.ultimate_title": "Full gauge",
		&"guide.ultimate_detail": "R after the level 3 unlock\\nClear the arena with your Ultimate",
		&"guide.resource_hint": "Dodge and Nullify share two defense charges. Save them for the moment that needs them.",
		&"guide.start": "Start Battle",
		&"guide.close": "Close",
		&"tutorial.hint_melee": "A close enemy can be cut down with Q.",
		&"tutorial.hint_negate": "Use E to clear bullets or close-quarters danger.",
		&"tutorial.hint_dodge": "When a heavy attack telegraphs move and dodge with W.",
		&"tutorial.hint_defense": "W and E share your defense charges.",
		&"tutorial.hint_ultimate": "Your level 3 Ultimate is unlocked. Press R to use it.",
		&"tutorial.skip": "Skip Tutorial",
		&"hud.training_time": "Training Time",
		&"hud.remaining_time": "Time Remaining",
		&"hud.training": "Training Grounds",
		&"hud.wave": "WAVE %d / %d",
		&"hud.unlimited": "No Time Limit",
		&"hud.in_progress": "In Progress",
		&"hud.paused": "Paused",
		&"hud.upgrade_select": "Choose Upgrade",
		&"hud.cleanup_wait": "Awaiting Cleanup",
		&"hud.clearing": "Clearing",
		&"hud.player_dead": "Defeated",
		&"hud.result": "Results",
		&"hud.challenge_reveal": "Rolling Debuff",
		&"hud.base_build": "Base Attack · No weapon selected",
		&"hud.challenge": "CHALLENGE · %s",
		&"hud.challenge_ready": "Preparing roulette",
		&"hud.level_max": "LV %d  ·  MAX",
		&"hud.level_xp": "LV %d  ·  XP %d / %d",
		&"action.attack": "Attack",
		&"action.dodge": "Dodge",
		&"action.negate": "Nullify",
		&"action.ultimate": "Ultimate",
		&"action.locked": "Locked",
		&"action.attack_cooldown_display": "Next slash in %.1f sec",
		&"action.defense_display": "Defense %d/%d",
		&"action.defense_locked_display": "Defense %d/%d\\nLocked",
		&"action.attack_tooltip_cooldown": "Attack\\nQ · Damage %d · Attack Speed %+d%%\\nNext attack in %.2f sec",
		&"action.attack_tooltip_ready": "Attack\\nQ · Damage %d · Attack Speed %+d%%\\nRange %d · Arc %d° · Recovery %.2f sec",
		&"action.dodge_tooltip": "Dodge\\nW · Invulnerable dash in your movement direction.\\nDefense %d/%d · Cost %d charge%s",
		&"action.dodge_twice_suffix": " · Can use twice",
		&"action.negate_tooltip": "Nullify\\nE · Spend one defense charge to remove enemies and projectiles.\\n%s",
		&"action.negate_disabled": "Unavailable while using the Dagger.",
		&"action.defense_state": "Defense charges %d/%d",
		&"action.ultimate_ready": "Ready",
		&"action.ultimate_charge": "Charge %d%%",
		&"action.ultimate_locked_detail": "Unlock a weapon Ultimate at level 3.",
		&"action.ultimate_select_detail": "Choose an Ultimate at level 3.",
		&"pause.title": "Paused",
		&"pause.hint": "Press Esc or the Ⅱ button to resume",
		&"pause.challenge": "Challenge · %s",
		&"pause.resume": "Resume",
		&"pause.restart": "Restart",
		&"pause.main": "Main Menu",
		&"pause.button_tooltip": "Pause · Esc",
		&"upgrade.hint": "Click a card or use the arrow keys + Enter to choose",
		&"upgrade.weapon_select": "Choose a Weapon",
		&"upgrade.technique_select": "[%s] Choose a Technique",
		&"upgrade.ultimate_unlock": "[%s] Unlock an Ultimate",
		&"upgrade.level_title": "LEVEL %d\\n%s",
		&"upgrade.role": "Combat choice",
		&"upgrade.fallback": "Upgrade",
		&"upgrade.immediate": "The weapon effect applies immediately.",
		&"upgrade.effect": "Effect · %s%s",
		&"upgrade.rule": "\\nRule · %s",
		&"upgrade.weakness": "Weakness · %s",
		&"upgrade.condition": "Condition · Applies immediately",
		&"upgrade.applied": "Upgrade applied · %s",
		&"upgrade.applied_detail": "The effect is now active.",
		&"training.controls_title": "Training Tools",
		&"training.controls_hint": "Choose a threat and test your build.",
		&"training.summon_group": "Summon Threats",
		&"training.field_group": "Field Management",
		&"training.navigation_group": "Training Menu",
		&"training.spawn_melee": "Melee Threat",
		&"training.spawn_ranged": "Ranged Threat",
		&"training.spawn_charger": "Charging Threat",
		&"training.spawn_volley": "Volley Threat",
		&"training.spawn_elite": "Elite Threat",
		&"training.enemy_melee_role": "Closes in for direct pressure",
		&"training.enemy_ranged_role": "Keeps distance and fires projectiles",
		&"training.enemy_charger_role": "Telegraphs a straight-line charge",
		&"training.enemy_volley_role": "Fills the arena with projectile volleys",
		&"training.enemy_elite_role": "A durable threat that drops a reward",
		&"training.clear": "Clear the Field",
		&"training.reset": "Reset Training",
		&"training.exit": "Leave Training",
		&"training.spawn_feedback": "Training enemy summoned · %s",
		&"training.reset_feedback": "Training reset",
		&"enemy.melee": "melee",
		&"enemy.ranged": "ranged",
		&"enemy.charger": "charger",
		&"enemy.volley": "volley",
		&"enemy.elite": "elite",
		&"challenge.title": "CHALLENGE MODE · Debuff Roulette",
		&"challenge.hint": "Roll one restriction for this run.",
		&"challenge.spinning": "Rolling roulette...",
		&"challenge.result": "Result locked · %s\\n%s",
		&"challenge.start": "Start Challenge",
		&"feedback.title_normal": "DON'T DODGE",
		&"feedback.title_challenge": "CHALLENGE · %s",
		&"feedback.training": "Training Grounds · No Time Limit",
		&"feedback.upgrade_applied": "%s applied%s",
		&"feedback.ultimate_ready_suffix": " · Ultimate ready · R",
		&"feedback.attack_miss": "Attack missed",
		&"feedback.dodge_pending": "Dodge readying",
		&"feedback.defense_empty": "Not enough defense charges",
		&"feedback.dagger_stealth": "Draw · Stealth",
		&"feedback.spear_breakthrough": "Breakthrough ready",
		&"feedback.dagger_negate_locked": "E locked · The Dagger focuses on dodging",
		&"feedback.front_guard": "Front guard",
		&"feedback.no_negate_target": "There is nothing to nullify",
		&"feedback.no_projectile": "No projectiles to block",
		&"feedback.bullet_cut": "Bullet Cut ready · Next Q fires three spear lines",
		&"feedback.ultimate_locked": "Ultimate locked · Unlock it at level 3",
		&"feedback.ultimate_charge": "Ultimate charge %d%%",
		&"feedback.ultimate_missing": "Ultimate effect unavailable",
		&"feedback.assassination_no_target": "Assassination Mark · No target",
		&"feedback.ground_suppression": "Ground Suppression · %d defeated · %d staggered",
		&"feedback.wave_pressure": "WAVE %d · PRESSURE UP",
		&"feedback.counter_ready": "Countered · Next attack empowered",
		&"feedback.perfect_dodge": "PERFECT · Precision dodge",
		&"feedback.ghost_step": "Ghost Step · Speed boost",
		&"feedback.elite_down": "ELITE DOWN · HEART DROPPED",
		&"feedback.ultimate_ready": "Ultimate ready · R",
		&"feedback.shadow_frenzy_complete": "Shadow Frenzy · %d target(s) cleared",
		&"feedback.assassination_complete": "Assassination Mark · Threat eliminated",
		&"feedback.ground_suppression_complete": "Ground Suppression complete",
		&"feedback.frontline_break_complete": "Frontline Break · Frontline breached",
		&"feedback.sky_pierce_complete": "Sky Pierce · Three pierces",
		&"feedback.spear_formation_complete": "Spear Formation · One pierce",
		&"result.clear": "90 seconds survived · WAVE %d cleared",
		&"result.death": "Defeated",
		&"result.normal_mode": "Standard Run",
		&"result.challenge_mode": "Challenge · %s",
		&"result.summary": "%s\\n%s\\nDefeated %d · Hits Taken %d · Dodges %d · Nullifies %d\\nPerfect Dodges %d · Interrupts %d · Projectiles Removed %d\\nUltimates %d",
		&"result.restart": "Restart",
		&"result.lobby": "Return to Lobby",
		&"data.dagger.title": "Dagger",
		&"data.dagger.subtitle": "A lethal weapon for rapid single-target takedowns",
		&"data.dagger.description": "Dash through danger with W, then chain fast single-target attacks.",
		&"data.dagger.detail": "Attack Speed +35% · Move Speed +8% · Single-target attacks",
		&"data.dagger.icon_label": "Offense",
		&"data.dagger.rule": "W-specialist · One target at a time",
		&"data.dagger.weakness": "Low health · E unavailable · Short range",
		&"data.tech_dagger_draw.title": "Quick Draw",
		&"data.tech_dagger_draw.description": "Vanish from enemy sight for a moment after W ends.",
		&"data.tech_dagger_draw.detail": "0.4 sec stealth after W · First attack from stealth deals +2 · Existing projectiles remain",
		&"data.tech_dagger_draw.icon_label": "Dodge follow-up",
		&"data.tech_dagger_flurry.title": "Flurry",
		&"data.tech_dagger_flurry.description": "The third attack continues into two single-target slashes.",
		&"data.tech_dagger_flurry.detail": "If the first target falls the second slash retargets nearby · Afterimage and distinct hit sound",
		&"data.tech_dagger_flurry.icon_label": "Combo attack",
		&"data.tech_dagger_ghost_step.title": "Ghost Step",
		&"data.tech_dagger_ghost_step.description": "Each takedown gives you a burst of speed toward the next target.",
		&"data.tech_dagger_ghost_step.detail": "Move Speed +20% for 0.6 sec after a takedown · Takedowns refresh the duration",
		&"data.tech_dagger_ghost_step.icon_label": "Movement boost",
		&"data.ult_dagger_shadow_frenzy.title": "Shadow Frenzy",
		&"data.ult_dagger_shadow_frenzy.description": "Cross the arena in a chain of slashes against up to three nearby enemies.",
		&"data.ult_dagger_shadow_frenzy.detail": "Up to 3 targets · Mark → dash → 4 damage per target · Invulnerable during the sequence",
		&"data.ult_dagger_shadow_frenzy.icon_label": "Multi-target assassination",
		&"data.ult_dagger_assassination_mark.title": "Assassination Mark",
		&"data.ult_dagger_assassination_mark.description": "Mark the greatest threat, blink behind it, and unleash a focused assault.",
		&"data.ult_dagger_assassination_mark.detail": "Prioritizes elites and chargers · Mark → dash behind target · Three hits for 4 damage each",
		&"data.ult_dagger_assassination_mark.icon_label": "Single-target assassination",
		&"data.guardian_mace.title": "Guardian Mace",
		&"data.guardian_mace.subtitle": "A sturdy weapon that holds the line from the front",
		&"data.guardian_mace.description": "Use E to guard projectiles and attacks from the front; W is an emergency dash costing two defense charges.",
		&"data.guardian_mace.detail": "Front guard · Strong knockback · Dodge costs 2 charges · Max health 3",
		&"data.guardian_mace.icon_label": "Defense",
		&"data.guardian_mace.rule": "E specialist · W costs 2 charges · Front guard",
		&"data.guardian_mace.weakness": "Slow movement · Vulnerable from the sides and rear · Defense-resource dependent",
		&"data.tech_mace_counter.title": "Counterstrike",
		&"data.tech_mace_counter.description": "After blocking with E, counter with a mace strike within 1.2 seconds.",
		&"data.tech_mace_counter.detail": "Next Q deals +2 after a successful guard · Stronger knockback · Interrupts attacks in preparation",
		&"data.tech_mace_counter.icon_label": "Counter boost",
		&"data.tech_mace_reflect_wave.title": "Reflective Wave",
		&"data.tech_mace_reflect_wave.description": "A reflected projectile sweeps through nearby enemies at the impact point.",
		&"data.tech_mace_reflect_wave.detail": "Reflected projectile creates a small shockwave · Hits up to 2 nearby enemies",
		&"data.tech_mace_reflect_wave.icon_label": "Reflect attack",
		&"data.tech_mace_suppress.title": "Suppressing Blow",
		&"data.tech_mace_suppress.description": "Break an enemy out of an attack wind-up with one mace strike.",
		&"data.tech_mace_suppress.detail": "Interrupts melee and charger wind-ups · Heavy-hit presentation · 2.5 sec internal cooldown",
		&"data.tech_mace_suppress.icon_label": "Attack interrupt",
		&"data.ult_mace_ground_suppression.title": "Ground Suppression",
		&"data.ult_mace_ground_suppression.description": "After a brief warning, slam the ground and control the arena around you.",
		&"data.ult_mace_ground_suppression.detail": "Warning → 360-degree shockwave · Defeats normal enemies · Damages and interrupts elites and chargers",
		&"data.ult_mace_ground_suppression.icon_label": "Area suppression",
		&"data.ult_mace_frontline_break.title": "Frontline Break",
		&"data.ult_mace_frontline_break.description": "Make a guarded dash toward the ranged line or your last movement direction.",
		&"data.ult_mace_frontline_break.detail": "Path warning → removes projectiles → area mace strike on arrival · Executes even without a target",
		&"data.ult_mace_frontline_break.icon_label": "Frontline breach",
		&"data.battle_spear.title": "Battle Spear",
		&"data.battle_spear.subtitle": "A weapon that cleaves the arena with long piercing lines",
		&"data.battle_spear.description": "Pierce enemies in a narrow line and chain W and E into your next attack.",
		&"data.battle_spear.detail": "Range +60 · Basic attacks pierce · Nullifies projectiles · Narrow attack arc",
		&"data.battle_spear.icon_label": "Piercing",
		&"data.battle_spear.rule": "Narrow long-range basic attack · Line pierce",
		&"data.battle_spear.weakness": "Narrow attack arc · Vulnerable in side-on chaos",
		&"data.tech_spear_breakthrough.title": "Breakthrough",
		&"data.tech_spear_breakthrough.description": "Stab an enemy with W to make your next attack pierce once more.",
		&"data.tech_spear_breakthrough.detail": "If W hits an enemy, the next Q gains an extra piercing strike for 0.8 sec",
		&"data.tech_spear_breakthrough.icon_label": "Dash follow-up",
		&"data.tech_spear_bullet_cut.title": "Bullet Cut",
		&"data.tech_spear_bullet_cut.description": "Clear a barrage with E to turn your next attack into three spear lines.",
		&"data.tech_spear_bullet_cut.detail": "Removing 2+ projectiles turns the next Q into a narrow three-line spear attack · Lasts 0.9 sec",
		&"data.tech_spear_bullet_cut.icon_label": "Barrage response",
		&"data.tech_spear_edge_pressure.title": "Edge Pressure",
		&"data.tech_spear_edge_pressure.description": "Pierce enemies at the edge of your range to bind their movement and attacks.",
		&"data.tech_spear_edge_pressure.detail": "Hits in the outer 30% of range slow and mark for 0.65 sec · Interrupts attacks in preparation",
		&"data.tech_spear_edge_pressure.icon_label": "Keep your distance",
		&"data.ult_spear_sky_pierce.title": "Sky Pierce",
		&"data.ult_spear_sky_pierce.description": "Pierce the warned line in one decisive strike.",
		&"data.ult_spear_sky_pierce.detail": "Based on a strong enemy or last movement direction · 3 pierces · 3 damage each · Executes without a target",
		&"data.ult_spear_sky_pierce.icon_label": "Line burst",
		&"data.ult_spear_formation.title": "Spear Formation",
		&"data.ult_spear_formation.description": "Draw a line from the player through the target across the screen, piercing once.",
		&"data.ult_spear_formation.detail": "Auto-aims marked targets first · Line reaches both map edges · One attack · 3 damage",
		&"data.ult_spear_formation.icon_label": "Area control",
		&"challenge.slow_defense.title": "Slow Defense Recovery",
		&"challenge.slow_defense.description": "Defense charge recovery takes 7 seconds instead of 5.",
		&"challenge.ultimate_famine.title": "Ultimate Famine",
		&"challenge.ultimate_famine.description": "Ultimate gain is reduced to 75%.",
		&"challenge.dry_dungeon.title": "Dry Dungeon",
		&"challenge.dry_dungeon.description": "Recovery items do not appear during combat.",
		&"challenge.bullet_overload.title": "Barrage Overload",
		&"challenge.bullet_overload.description": "Volley enemies fire one extra projectile.",
	},
}


var _locale: StringName = DEFAULT_LOCALE


func _ready() -> void:
	_locale = _load_saved_locale()


func current_locale() -> StringName:
	return _locale


func set_locale(locale: StringName, persist: bool = true) -> void:
	var next_locale: StringName = locale if SUPPORTED_LOCALES.has(locale) else DEFAULT_LOCALE
	var changed: bool = _locale != next_locale
	_locale = next_locale
	if persist:
		_save_locale()
	if changed:
		locale_changed.emit(_locale)


func translate(key: StringName, arguments: Array = []) -> String:
	var message_key: StringName = key
	var locale_catalog: Dictionary = CATALOG.get(str(_locale), {})
	var text: String = str(locale_catalog.get(message_key, message_key))
	text = _normalize_text(text)
	if arguments.is_empty():
		return text
	return text % arguments


func _normalize_text(text: String) -> String:
	return text.replace("\\n", "\n")


func has_key(key: StringName, locale: StringName = &"") -> bool:
	var target_locale: StringName = _locale if locale.is_empty() else locale
	var locale_catalog: Dictionary = CATALOG.get(str(target_locale), {})
	return locale_catalog.has(key) and not str(locale_catalog[key]).strip_edges().is_empty()


func validate_catalog(required_keys: Array[StringName] = []) -> PackedStringArray:
	var errors := PackedStringArray()
	for locale: StringName in SUPPORTED_LOCALES:
		if not CATALOG.has(str(locale)):
			errors.append("missing locale column: %s" % locale)
	for locale: StringName in SUPPORTED_LOCALES:
		var locale_catalog: Dictionary = CATALOG.get(str(locale), {})
		for key: StringName in required_keys:
			if not locale_catalog.has(key):
				errors.append("missing %s translation: %s" % [locale, key])
			elif str(locale_catalog[key]).strip_edges().is_empty():
				errors.append("empty %s translation: %s" % [locale, key])
	return errors


func get_supported_locales() -> Array[StringName]:
	return SUPPORTED_LOCALES.duplicate()


func get_catalog_keys() -> Array[StringName]:
	var keys: Array[StringName] = []
	for locale: StringName in SUPPORTED_LOCALES:
		for key: Variant in CATALOG.get(str(locale), {}).keys():
			var typed_key := StringName(str(key))
			if not keys.has(typed_key):
				keys.append(typed_key)
	return keys


func _load_saved_locale() -> StringName:
	var settings := ConfigFile.new()
	if settings.load(SETTINGS_PATH) != OK:
		return DEFAULT_LOCALE
	var saved_locale: StringName = StringName(str(settings.get_value(SETTINGS_SECTION, SETTINGS_KEY, str(DEFAULT_LOCALE))))
	return saved_locale if SUPPORTED_LOCALES.has(saved_locale) else DEFAULT_LOCALE


func _save_locale() -> void:
	var settings := ConfigFile.new()
	if settings.load(SETTINGS_PATH) != OK:
		settings = ConfigFile.new()
	settings.set_value(SETTINGS_SECTION, SETTINGS_KEY, str(_locale))
	if settings.save(SETTINGS_PATH) != OK:
		push_warning("Could not save DON’T DODGE locale setting.")
